### ISSUE TITLE
Transfer to OSP orga

### ISSUE THREAD

**Issue by PavelBal** [pchelle/OSPSuite.Addins#5]
Do you plan to make an "official" repo in the OSP organization? I think this is great stuff here! Will also be happy to contribute.

**Comment by pchelle** [comment]
>I think this is great stuff here! Will also be happy to contribute.

Thanks @PavelBal :)

> Do you plan to make an "official" repo in the OSP organization? 

Initially, I was only testing out how addins worked.
Why not, if you think it may be helpful for everyone.

**Comment by pchelle** [comment]
Just forked it :)
